---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- apt:
    name: incron
    state: present
    force_apt_get: yes
  environment:
    http_proxy: '{{ http_proxy }}'
    https_proxy: '{{ https_proxy }}'

- command: 'echo $http_proxy'
  environment:
    http_proxy: '{{ http_proxy }}'
    https_proxy: '{{ https_proxy }}'
