---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- include_tasks: centOS.yml
  when: ansible_os_family == "RedHat"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: install autoarchive script
  copy:
    src: scratch_versioning
    dest: /usr/bin
    mode: 0755

- name: create archive directory
  file:
    path: '/home/{{installation_os_user}}/archive'
    state: directory
    owner: '{{ installation_os_user }}'
    group: '{{ installation_os_group }}'

- name: configure autorun if file touched
  lineinfile:
    path: '/var/spool/incron/{{ installation_os_user }}'
    line: "/home/{{ installation_os_user }}/ IN_CREATE /usr/bin/scratch_versioning $@ $#"
    owner: '{{ installation_os_user }}'
    group: '{{ installation_os_group }}'
    create: true
    mode: 500
  register: incron

- name: allow user to use incron
  lineinfile:
   dest: /etc/incron.allow
   state: present
   create: yes
   line: '{{ installation_os_user }}'

- name: activate incron configure
  command: 'incrontab -u {{ installation_os_user }} -d'
  when: incron.changed
